/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kentank-ID
 */
public class frmTransaksi2 extends javax.swing.JFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    Connection con;
    PreparedStatement statement = null;
    DefaultTableModel dataModel = new DefaultTableModel();

    final String queryIdKons = "select nm_kons from konsumen where kd_kons=?";
    final String queryIdBrg = "select nm_brg, harga from barang where kd_brg=?";
    final String queryNoJual = "select max(no_jual) from jual";
    final String queryInsert = "insert into jual (no_jual, kd_kons, tgl_jual) values (?,?,?)";
    final String queryInsertDB = "insert into djual (no_jual, kd_brg, harga_jual, jml_jual) values (?,?,?,?)";
    final String queryInsertTransaksi = "insert into transaksi (no_jual, tot_harga, bayar, kembali) values (?,?,?,?)";

    static int temp;

    /**
     * Creates new form frmTransaksi2
     */
    public frmTransaksi2() {
        initComponents();
        con = koneksiMYSQL.getConnection();
        setNoJual();

        dataModel.addColumn("kode");
        dataModel.addColumn("nama");
        dataModel.addColumn("harga");
        dataModel.addColumn("jumlah");
        dataModel.addColumn("total");

        //set editable
        jTextFieldNmKons.setEditable(false);
        jTextFieldDtlNmBrg.setEditable(false);
        jTextFieldDtlHrgBrg.setEditable(false);
        jTextFieldDtlTotHrg.setEditable(false);
        jTextFieldNoJual.setEditable(false);
        jTextFieldKembali.setEditable(false);
        jTextFieldTotAll.setEditable(false);

    }

    public void setDate() {
        String tampung = sdf.format(jDateChooserTglJual.getDate());
        System.out.println(tampung);
    }

    public void setNoJual() {
        try {
            statement = con.prepareStatement(queryNoJual);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                temp = Integer.parseInt(rs.getString(1));
                temp += 1;
                jTextFieldNoJual.setText(String.valueOf(temp));
            }
        } catch (SQLException e) {
            System.out.println("gagal " + e);
        }
    }

    public void tampungTabel() {

//            ArrayList dataInput = new ArrayList();
//            jTableKeranjang.setAutoCreateColumnsFromModel(true);
        if (!jTextFieldDtlJmlBrg.getText().isBlank() || !jTextFieldDtlJmlBrg.getText().isEmpty()) {
            String data1 = jComboBoxKdBrg.getSelectedItem().toString();
            String data2 = jTextFieldDtlNmBrg.getText();
            String data3 = jTextFieldDtlHrgBrg.getText();
            String data4 = jTextFieldDtlJmlBrg.getText();
            String data5 = jTextFieldDtlTotHrg.getText();
            Object[] row = {data1, data2, data3, data4, data5};
            dataModel.addRow(row);
            jTableKeranjang.setModel(dataModel);
        }

    }

    public void setTotalAll() {
        int row = jTableKeranjang.getRowCount();
        float total = 0;
        for (int j = 0; j < row; j++) {
            String tempTotal = (String) jTableKeranjang.getValueAt(j, 4);
            float tempTotal2 = Float.parseFloat(tempTotal);
            total += tempTotal2;
        }
        System.out.println(total);
        jTextFieldTotAll.setText(Float.toString(total));
    }

    public void setKembali() {
        float total = Float.parseFloat(jTextFieldTotAll.getText());
        float bayar = Float.parseFloat(jTextFieldBayar.getText());
        if (jTableKeranjang.getRowCount() == 0) {
            jTextFieldKembali.setText("0");
        } else if (bayar < total) {
            jTextFieldKembali.setText("Uang Kurang");
        } else {
            float kembali = bayar - total;
            jTextFieldKembali.setText(Float.toString(kembali));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNoJual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserTglJual = new com.toedter.calendar.JDateChooser();
        jButtonTambah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxKdKons = new javax.swing.JComboBox<>();
        jTextFieldNmKons = new javax.swing.JTextField();
        jComboBoxKdBrg = new javax.swing.JComboBox<>();
        jTextFieldDtlNmBrg = new javax.swing.JTextField();
        jTextFieldDtlHrgBrg = new javax.swing.JTextField();
        jTextFieldDtlJmlBrg = new javax.swing.JTextField();
        jTextFieldDtlTotHrg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKeranjang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabelBayar = new javax.swing.JLabel();
        jLabelKembali = new javax.swing.JLabel();
        jTextFieldTotAll = new javax.swing.JTextField();
        jTextFieldBayar = new javax.swing.JTextField();
        jTextFieldKembali = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No. Jual");

        jLabel2.setText("Tgl. Jual");

        jButtonTambah.setText("Checkout");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Konsumen");

        jComboBoxKdKons.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","000001", "000002", "000003"}));
        jComboBoxKdKons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKdKonsActionPerformed(evt);
            }
        });
        jComboBoxKdKons.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxKdKonsKeyPressed(evt);
            }
        });

        jComboBoxKdBrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "B-0001", "B-0002", "B-0003", "B-0004" }));
        jComboBoxKdBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKdBrgActionPerformed(evt);
            }
        });

        jTextFieldDtlNmBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDtlNmBrgActionPerformed(evt);
            }
        });

        jTextFieldDtlJmlBrg.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDtlJmlBrgCaretUpdate(evt);
            }
        });
        jTextFieldDtlJmlBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDtlJmlBrgActionPerformed(evt);
            }
        });
        jTextFieldDtlJmlBrg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldDtlJmlBrgPropertyChange(evt);
            }
        });
        jTextFieldDtlJmlBrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDtlJmlBrgKeyTyped(evt);
            }
        });
        jTextFieldDtlJmlBrg.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTextFieldDtlJmlBrgVetoableChange(evt);
            }
        });

        jTextFieldDtlTotHrg.setText("0");

        jLabel4.setText("=");

        jLabel7.setText("jumlah");

        jLabel9.setText("kode barang");

        jTableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kode", "nama", "harga", "jumlah", "total"
            }
        ));
        jScrollPane1.setViewportView(jTableKeranjang);

        jLabel5.setText("Keranjang");

        jButton1.setText("Pilih Barang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelTotal.setText("Total");

        jLabelBayar.setText("Bayar");

        jLabelKembali.setText("Kembali");

        jTextFieldTotAll.setText("0.0");
        jTextFieldTotAll.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldTotAllCaretUpdate(evt);
            }
        });

        jTextFieldBayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldBayarCaretUpdate(evt);
            }
        });

        jTextFieldKembali.setText("0");

        jButton2.setText("Hapus Barang");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cetak Nota");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextAreaNota.setColumns(20);
        jTextAreaNota.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNoJual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserTglJual, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxKdKons, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNmKons, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBoxKdBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldDtlNmBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldDtlHrgBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldDtlJmlBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldDtlTotHrg)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabelKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabelBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jTextFieldTotAll, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextFieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextFieldKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonTambah)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNoJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxKdKons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNmKons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jDateChooserTglJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxKdBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDtlNmBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDtlHrgBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDtlJmlBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDtlTotHrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButton2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal)
                    .addComponent(jButton4))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBayar))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKembali))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTambah)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        //queryInsert
        try {
            statement = con.prepareStatement(queryInsert);
            statement.setString(1, jTextFieldNoJual.getText());
            String temp = jComboBoxKdKons.getSelectedItem().toString();
            statement.setString(2, temp);
//            Date date = jDateChooserTglJual.getDate();
//            String strDate = DateFormat.getDateInstance().format(date);
//            statement.setString(3, strDate);
            java.util.Date utilStartDate = jDateChooserTglJual.getDate();
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            statement.setDate(3, sqlStartDate);
            statement.executeUpdate();
            System.out.println("sukses");
        } catch (SQLException e) {
            System.out.println("gagal insert " + e);
        }

        //queryInsertDB
        int row = jTableKeranjang.getRowCount();
        int column = jTableKeranjang.getColumnCount();
        for (int j = 0; j < row; j++) {
            String data0 = "";
            String data1 = "";
            String data2 = "";
            String data3 = "";
            String data4 = "";
            for (int i = 0; i < column; i++) {
                switch (i) {
                    case 0:
                        data0 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 1:
                        data1 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 2:
                        data2 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 3:
                        data3 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 4:
                        data4 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                }
            }
            System.out.println(data0 + data1 + data2 + data3 + data4);
            try {
                statement = con.prepareStatement(queryInsertDB);
                statement.setString(1, jTextFieldNoJual.getText());
                statement.setString(2, data0);
                statement.setString(3, data2);
                statement.setString(4, data3);
                statement.executeUpdate();
                System.out.println("sukses");
            } catch (SQLException e) {
                System.out.println("gagal " + e);
            }
            System.out.println("---------------");
        }

        //queryInsertTransaksi
        try {
            statement = con.prepareStatement(queryInsertTransaksi);
            statement.setString(1, jTextFieldNoJual.getText());
            statement.setString(2, jTextFieldTotAll.getText());
            statement.setString(3, jTextFieldBayar.getText());
            statement.setString(4, jTextFieldKembali.getText());
            statement.executeUpdate();
            System.out.println("sukses transaksi");
        } catch (SQLException e) {
            System.out.println("gagal " + e);
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jComboBoxKdKonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKdKonsActionPerformed
        // TODO add your handling code here:
        String index = jComboBoxKdKons.getSelectedItem().toString();
        try {
            statement = con.prepareStatement(queryIdKons);
            statement.setString(1, index);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                jTextFieldNmKons.setText(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println("gagal " + e);
        }
    }//GEN-LAST:event_jComboBoxKdKonsActionPerformed

    private void jComboBoxKdKonsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxKdKonsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKdKonsKeyPressed

    private void jTextFieldDtlNmBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDtlNmBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDtlNmBrgActionPerformed

    private void jComboBoxKdBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKdBrgActionPerformed
        // TODO add your handling code here:
        String index = jComboBoxKdBrg.getSelectedItem().toString();
        try {
            statement = con.prepareStatement(queryIdBrg);
            statement.setString(1, index);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                jTextFieldDtlNmBrg.setText(rs.getString(1));
                jTextFieldDtlHrgBrg.setText(rs.getString(2));
            }
        } catch (SQLException e) {
            System.out.println("gagal " + e);
        }
    }//GEN-LAST:event_jComboBoxKdBrgActionPerformed

    private void jTextFieldDtlJmlBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDtlJmlBrgActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(jTextFieldDtlJmlBrg.getText());
        int harga = Integer.parseInt(jTextFieldDtlHrgBrg.getText());
        int total = jumlah * harga;
        jTextFieldDtlTotHrg.setText(String.valueOf(total));
    }//GEN-LAST:event_jTextFieldDtlJmlBrgActionPerformed

    private void jTextFieldDtlJmlBrgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldDtlJmlBrgPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldDtlJmlBrgPropertyChange

    private void jTextFieldDtlJmlBrgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDtlJmlBrgKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDtlJmlBrgKeyTyped

    private void jTextFieldDtlJmlBrgVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTextFieldDtlJmlBrgVetoableChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldDtlJmlBrgVetoableChange

    private void jTextFieldDtlJmlBrgCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDtlJmlBrgCaretUpdate
        // TODO add your handling code here:
        System.out.println(evt);
        try {
            System.out.println("ada isi");
            float jumlah = Float.parseFloat(jTextFieldDtlJmlBrg.getText());
            float harga = Float.parseFloat(jTextFieldDtlHrgBrg.getText());
            float total = jumlah * harga;
            jTextFieldDtlTotHrg.setText(String.valueOf(total));
        } catch (NumberFormatException nfe) {
            System.out.println(nfe);
            jTextFieldDtlTotHrg.setText(String.valueOf(0));
        }
    }//GEN-LAST:event_jTextFieldDtlJmlBrgCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tampungTabel();
        setTotalAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dataModel.removeRow(jTableKeranjang.getSelectedRow());
        setTotalAll();
        setKembali();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldBayarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldBayarCaretUpdate
        // TODO add your handling code here:
        setKembali();

    }//GEN-LAST:event_jTextFieldBayarCaretUpdate

    private void jTextFieldTotAllCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldTotAllCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotAllCaretUpdate

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            jTextAreaNota.print();
        } catch (PrinterException ex) {
            Logger.getLogger(frmTransaksi2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextAreaNota.append("No. Jual \t: "+jTextFieldNoJual.getText() + "\n");
        jTextAreaNota.append("Tanggal \t: "+jDateChooserTglJual.getDate().toString() + "\n");
        jTextAreaNota.append("Kode \t: "+jComboBoxKdKons.getSelectedItem().toString() + "\n");
        jTextAreaNota.append("Nama \t: "+jTextFieldNmKons.getText() + "\n\n");
        int row = jTableKeranjang.getRowCount();
        int column = jTableKeranjang.getColumnCount();
        jTextAreaNota.append("KODE \tNAMA \tHARGA \tJUMLAH \tTOTAL\n");
        jTextAreaNota.append("--------------------------------------------------------------------------------------------------------\n");
        for (int j = 0; j < row; j++) {
            String data0 = "";
            String data1 = "";
            String data2 = "";
            String data3 = "";
            String data4 = "";
            for (int i = 0; i < column; i++) {
                System.out.println(jTableKeranjang.getValueAt(j, i));
                switch (i) {
                    case 0:
                        data0 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 1:
                        data1 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 2:
                        data2 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 3:
                        data3 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                    case 4:
                        data4 = (String) jTableKeranjang.getValueAt(j, i);
                        break;
                }
            }
            jTextAreaNota.append(data0+"\t"+data1+"\t"+data2+"\t"+data3+"\t"+data4+"\n");
        }
        jTextAreaNota.append("\nTotal Harga \t: "+jTextFieldTotAll.getText());
        jTextAreaNota.append("\nBayar \t: "+jTextFieldBayar.getText());
        jTextAreaNota.append("\nKembali \t: "+jTextFieldKembali.getText());
        jTextAreaNota.append("\n\nTERIMAKASIH TELAH BELANJA :)");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransaksi2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JComboBox<String> jComboBoxKdBrg;
    private javax.swing.JComboBox<String> jComboBoxKdKons;
    private com.toedter.calendar.JDateChooser jDateChooserTglJual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBayar;
    private javax.swing.JLabel jLabelKembali;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableKeranjang;
    private javax.swing.JTextArea jTextAreaNota;
    private javax.swing.JTextField jTextFieldBayar;
    private javax.swing.JTextField jTextFieldDtlHrgBrg;
    private javax.swing.JTextField jTextFieldDtlJmlBrg;
    private javax.swing.JTextField jTextFieldDtlNmBrg;
    private javax.swing.JTextField jTextFieldDtlTotHrg;
    private javax.swing.JTextField jTextFieldKembali;
    private javax.swing.JTextField jTextFieldNmKons;
    private javax.swing.JTextField jTextFieldNoJual;
    private javax.swing.JTextField jTextFieldTotAll;
    // End of variables declaration//GEN-END:variables
}

//class PrintingTask extends SwingWorker<Object, Object> { 
//    private final MessageFormat headerFormat; 
//    private final MessageFormat footerFormat; 
//    private final boolean interactive; 
//    private volatile boolean complete = false; 
//    private volatile String message; 
//    public PrintingTask(MessageFormat header, MessageFormat footer,boolean interactive) { 
//        this.headerFormat = header; 
//        this.footerFormat = footer; 
//        this.interactive = interactive; 
//    } 
//    @Override 
//    protected Object doInBackground() { 
//        try { 
//            complete = text.print(headerFormat, footerFormat, 
//            true, null, null, interactive); 
//            message = "Printing " + (complete ? "complete" :"canceled"); 
//        } catch (PrinterException ex) { 
//            message = "Sorry, a printer error occurred"; 
//        } catch (SecurityException ex) { 
//            message = "Sorry, cannot access the printer due to security reasons";
//        } 
//        return null; 
//    } 
//    @Override 
//    protected void done() { 
//        message(!complete, message); 
//    } 
// }
